### PR TITLE
Fixed cert update race condition

### LINKED ISSUE #341: Irrelevant error logs, presumably due to a race condition
Hi! First of all, thank you far an amazing project! We are currently implementing it and it seems to work great!

The only issue I see is the irrelevant logging form controller-runtime reconciliation loop - something like this:

```
2025-02-26T13:36:07Z    ERROR   cert-rotation   could not refresh CA and server certs   {"error": "Operation cannot be fulfilled on secrets \"operator-webhook-server-cert\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).refreshCertIfNeeded.func1
        /go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.12.0/pkg/rotator/rotator.go:329
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection
        /go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/wait/wait.go:145
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
        /go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/wait/backoff.go:461
github.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).refreshCertIfNeeded
        /go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.12.0/pkg/rotator/rotator.go:357
github.com/open-policy-agent/cert-controller/pkg/rotator.(*CertRotator).Start
        /go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.12.0/pkg/rotator/rotator.go:285
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/manager/runnable_group.go:226
```
and

```
2025-02-27T12:22:20Z    ERROR   cert-rotation   secret is not well-formed, cannot update webhook configurations {"error": "Cert secret is not well-formed, missing ca.crt", "errorVerbose": "Cert secret is not well-formed, missing ca.crt\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.buildArtifactsFromSecret\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.12.0/pkg/rotator/rotator.go:508\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.12.0/pkg/rotator/rotator.go:784\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"}
github.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile
        /go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.12.0/pkg/rotator/rotator.go:786
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224
```

I believe that's because the cert-controller's reconciliation loop and the 'runable' (`Start() function`) are trying to both reference the same secret concurrently. My question is - am I right, or am I doing something wrong here? If I am right and the race condition really occurs, is there any reason not to sync those, so reconciliation would be halted until the runable finishes cert creation and mount? I've created small PR just for tests and it seems to fix the logging issue for me.

### PR DESCRIPTION
**Pull request by p-strusiewiczsurmacki-mobica**
This PR should fix #341

It adds check for `certsMounted` channel in reconciliation loop, so reconciliation will only start if all the certs are ready and mounted. This suppresses the irrelevant errors emitted by controller-runtime due to reconciliation loop and runable accessing same secret concurrently.

### CODE REVIEW

File: pkg/rotator/rotator.go [hunk 1]
```diff
@@ -752,6 +760,10 @@ func (r *ReconcileWH) Reconcile(ctx context.Context, request reconcile.Request)
 		return reconcile.Result{}, nil
 	}
 
+	if r.enableReadinessCheck {
+		<-r.certsMounted
```
Comment (ritazh) [inline pkg/rotator/rotator.go:764]: Thanks for the PR @p-strusiewiczsurmacki-mobica !

This change in the Reconcile function and the readiness check mechanism using channel certsMounted can potentially lead to blocking behavior in the Reconcile function if the `ensureCertsMounted` function fails to close certsMounted. Instead, we can add a retry mechanism to handle failure cases.

```suggestion
 select {
    case <-r.certsMounted:
        // Continue with reconciliation
    case <-r.certsNotMounted:
        // Requeue with backoff strategy
        return reconcile.Result{Requeue: true, RequeueAfter: 5 * time.Second}, errors.New("certs not mounted, retrying reconciliation")
    }
```

Comment (p-strusiewiczsurmacki-mobica) [reply pkg/rotator/rotator.go]: Thank you! That's cleaver! Didn't think of that, tbh.

Comment (enj) [reply pkg/rotator/rotator.go]: In the `<-r.certsNotMounted` case I would `return reconcile.Result{}, errors.New("certs not mounted, retrying reconciliation")`.  For completeness I would also check `ctx.Done`.

File: pkg/rotator/rotator.go [hunk 2]
```diff
@@ -752,6 +760,16 @@ func (r *ReconcileWH) Reconcile(ctx context.Context, request reconcile.Request)
 		return reconcile.Result{}, nil
 	}
 
+	if r.enableReadinessCheck {
+ select {
+    case <-r.certsMounted:
+        // Continue with reconciliation
+    case <-r.certsNotMounted:
+        // Requeue with backoff strategy
+        return reconcile.Result{Requeue: true, RequeueAfter: 5 * time.Second}, errors.New("certs not mounted, retrying reconciliation")
```
Comment (enj) [inline pkg/rotator/rotator.go:769]: In the `<-r.certsNotMounted` case I would `return reconcile.Result{}, errors.New("certs not mounted, retrying reconciliation")`.  For completeness I would also check `ctx.Done`.

File: pkg/rotator/rotator.go (hunk 1 above)
Comment (p-strusiewiczsurmacki-mobica) [reply pkg/rotator/rotator.go]: After some consideration I think need to think this one more thoroughly. If `certsNotMounted` is closed, then Rotator emits error and quits I believe. So there might be no point in waiting for it.

Comment (p-strusiewiczsurmacki-mobica) [reply pkg/rotator/rotator.go]: I've changed the approach to use context's timeout for check. Please let me know what do you think about this one.

File: pkg/rotator/rotator.go (hunk 2 above)
Comment (p-strusiewiczsurmacki-mobica) [reply pkg/rotator/rotator.go]: I've added the check for `ctx.Done`.

File: pkg/rotator/rotator.go (hunk 1 above)
Comment (ritazh) [reply pkg/rotator/rotator.go]: @p-strusiewiczsurmacki-mobica I think your previous implementation is cleaner if you include the suggestion here with this update

```go
 select {
    case <-r.certsMounted:
        // Continue with reconciliation
    case <- ctx.Done():
       // Continue with reconciliation
    case <-r.certsNotMounted:
        // controller-runtime will requeue with backoff strategy when this error is returned
        return reconcile.Result{}, errors.New("certs not mounted, retrying reconciliation")
  } 
```

Per controller-runtime:
> // If the returned error is non-nil, the Result is ignored and the request will be
	// requeued using exponential backoff.

https://github.com/kubernetes-sigs/controller-runtime/blob/d8b679322d5cc466d12301b8875c42040fd29e46/pkg/reconcile/reconcile.go#L112-L114

Comment (p-strusiewiczsurmacki-mobica) [reply pkg/rotator/rotator.go]: @ritazh OK, I've updated the code.

**Comment by dhanushmuralidharan** [comment]
Hi,
@p-strusiewiczsurmacki-mobica Thanks for the PR. We faced a similar issue (Errors on operator startup presumably due to a race condition). I tried making the changes you have proposed and it seemed to work. I'm waiting on this PR to be merged. Is there any other way to resolve the error or fix this [issue](https://github.com/open-policy-agent/cert-controller/issues/341)?

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @dhanushmuralidharan 

Only thing that worked for me was to enable the `RestartOnSecretRefresh` flag. But that's rather a workaround.

**Review by ritazh — APPROVED** [review]
LGTM

Thanks for the PR @p-strusiewiczsurmacki-mobica

**Review by JaydipGabani — APPROVED** [review]
LGTM

File: pkg/rotator/rotator.go [hunk 3]
```diff
@@ -743,6 +750,9 @@ type ReconcileWH struct {
 	needLeaderElection          bool
 	refreshCertIfNeededDelegate func() (bool, error)
 	fieldOwner                  string
+	certsMounted                chan struct{}
+	certsNotMounted             chan struct{}
+	enableReadinessCheck        bool
```
Comment (ritazh) [inline pkg/rotator/rotator.go:755]: @JaydipGabani  when you bump this in Gatekeeper, don't forget to set this.
